SOFA_DIR = ../../..
TEMPLATE = lib
include($${SOFA_DIR}/sofa.cfg)
TARGET = sofacomponent$$LIBSUFFIX
CONFIG += $$CONFIGLIBRARIES
 
HEADERS += MappedObject.h \
           MappedObject.inl \
           MechanicalObject.h \
           MechanicalObject.inl \
           FreeJoint.h \
           Joint.h \
           RevoluteJoint.h \
           ArticulatedBody.h \
           behaviormodel/eulerianfluid/Fluid2D.h \
           behaviormodel/eulerianfluid/Fluid3D.h \
           behaviormodel/eulerianfluid/Grid2D.h \
           behaviormodel/eulerianfluid/Grid3D.h \
           behaviormodel/eulerianfluid/SpatialGridContainer.h \
           behaviormodel/eulerianfluid/SpatialGridContainer.inl \
           collision/BarycentricContactMapper.h \
           collision/BarycentricLagrangianMultiplierContact.h \
           collision/BarycentricLagrangianMultiplierContact.inl \
           collision/BarycentricPenalityContact.h \
           collision/BarycentricPenalityContact.inl \
           collision/BarycentricStickContact.h \
           collision/BarycentricStickContact.inl \
           collision/BruteForceDetection.h \
           collision/ContactCorrection.h \
           collision/ContactCorrection.inl \
           collision/ContinuousIntersection.h \
           collision/ContinuousTriangleIntersection.h \
           collision/Cube.h \
           collision/CubeModel.h \
           collision/CuttingManager.h \
           collision/CarvingManager.h \
           collision/DefaultCollisionGroupManager.h \
           collision/DefaultContactManager.h \
           collision/DefaultPipeline.h \
           collision/DiscreteIntersection.h \
           collision/DiscreteIntersection.inl \
           collision/DistanceGridCollisionModel.h \
           collision/EdgeRemoveContact.h \
           collision/FractureManager.h \
           collision/FrictionContact.h \
           collision/FrictionContact.inl \
           collision/GraspingManager.h \
           collision/Line.h \
           collision/LineModel.h \
           collision/MinProximityIntersection.h \
           collision/NewProximityIntersection.h \
           collision/NewProximityIntersection.inl \
           collision/RayTraceDetection.h \
           collision/Point.h \
           collision/PointModel.h \
           collision/proximity.h \
           collision/ProximityIntersection.h \
           collision/Ray.h \
           collision/RayContact.h \
           collision/RayModel.h \
           collision/RayPickInteractor.h \
           collision/RayTriangleIntersection.h \
           collision/SharpLineModel.h \
           collision/Sphere.h \
           collision/SphereModel.h \
           collision/SphereModel.inl \
           collision/SphereTreeModel.h \
           collision/TestDetection.h \
           collision/Triangle.h \
           collision/TriangleModel.h \
           collision/TriangleOctree.h \
           collision/TriangleOctreeModel.h \
	   collision/TriangularFEMFractureManager.h \
           constraint/BoxConstraint.h \
           constraint/BoxConstraint.inl \
           constraint/FixedConstraint.h \
           constraint/FixedConstraint.inl \
           constraint/FixedPlaneConstraint.h \
           constraint/FixedPlaneConstraint.inl \
           constraint/LagrangianMultiplierAttachConstraint.h \
           constraint/LagrangianMultiplierAttachConstraint.inl \
           constraint/LagrangianMultiplierConstraint.h \
           constraint/LagrangianMultiplierContactConstraint.h \
           constraint/LagrangianMultiplierContactConstraint.inl \
           constraint/LagrangianMultiplierFixedConstraint.h \
           constraint/LagrangianMultiplierFixedConstraint.inl \
           constraint/OscillatorConstraint.h \
           constraint/OscillatorConstraint.inl \
           constraint/UnilateralInteractionConstraint.h \
           constraint/UnilateralInteractionConstraint.inl \
           constraint/LinearMovementConstraint.h \
           constraint/LinearMovementConstraint.inl \
           container/ArticulatedHierarchyContainer.h \
           container/ArticulatedHierarchyContainer.inl \
           contextobject/CoordinateSystem.h \
           contextobject/Gravity.h \
           contextobject/GuidedCoordinateSystem.h \
           forcefield/BeamFEMForceField.h \
           forcefield/BeamFEMForceField.inl \
           forcefield/ConstantForceField.h \
           forcefield/ConstantForceField.inl \
           forcefield/EdgePressureForceField.h \
           forcefield/EdgePressureForceField.inl \
           forcefield/LennardJonesForceField.h \
           forcefield/LennardJonesForceField.inl \
           forcefield/SPHFluidForceField.h \
           forcefield/SPHFluidForceField.inl \
           forcefield/PlaneForceField.h \
           forcefield/PlaneForceField.inl \
           forcefield/SphereForceField.h \
           forcefield/SphereForceField.inl \
           forcefield/ConicalForceField.h \
           forcefield/ConicalForceField.inl \
           forcefield/EllipsoidForceField.h \
           forcefield/EllipsoidForceField.inl \
           forcefield/PenalityContactForceField.h \
           forcefield/PenalityContactForceField.inl \
           forcefield/QuadBendingSprings.h \
           forcefield/QuadBendingSprings.inl \
           forcefield/SpringForceField.h \
           forcefield/SpringForceField.inl \
           forcefield/StiffSpringForceField.h \
           forcefield/StiffSpringForceField.inl \
           forcefield/JointSpringForceField.h \
           forcefield/JointSpringForceField.inl \
           forcefield/MeshSpringForceField.h \
           forcefield/MeshSpringForceField.inl \
           forcefield/RegularGridSpringForceField.h \
           forcefield/RegularGridSpringForceField.inl \
           forcefield/TensorForceField.h \
           forcefield/TetrahedronFEMForceField.h \
           forcefield/TetrahedronFEMForceField.inl \
           forcefield/HexahedronFEMForceField.h \
           forcefield/HexahedronFEMForceField.inl \
	   forcefield/HexahedronFEMForceFieldAndMass.h \
	   forcefield/HexahedronFEMForceFieldAndMass.inl \
           forcefield/TetrahedralTensorMassForceField.h \
           forcefield/TetrahedralTensorMassForceField.inl \
           forcefield/TetrahedralBiquadraticSpringsForceField.h \
           forcefield/TetrahedralBiquadraticSpringsForceField.inl \
           forcefield/TetrahedralQuadraticSpringsForceField.h \
           forcefield/TetrahedralQuadraticSpringsForceField.inl \
           forcefield/TetrahedralCorotationalFEMForceField.h \
           forcefield/TetrahedralCorotationalFEMForceField.inl \
           forcefield/TriangleBendingSprings.h \
           forcefield/TriangleBendingSprings.inl \
	     forcefield/TriangularBendingSprings.h \
           forcefield/TriangularBendingSprings.inl \
           forcefield/TriangleFEMForceField.h \
	     forcefield/TriangularFEMForceField.h \
           forcefield/TrianglePressureForceField.h \
           forcefield/TrianglePressureForceField.inl \
           forcefield/TriangularBiquadraticSpringsForceField.h \
           forcefield/TriangularBiquadraticSpringsForceField.inl \
           forcefield/TriangularQuadraticSpringsForceField.h \
           forcefield/TriangularQuadraticSpringsForceField.inl \
           forcefield/TriangularTensorMassForceField.h \
           forcefield/TriangularTensorMassForceField.inl \
           forcefield/VectorSpringForceField.h \
           forcefield/VectorSpringForceField.inl \
           forcefield/WashingMachineForceField.h \
           forcefield/WashingMachineForceField.inl \
           interactionforcefield/ExternalForceField.h \
           interactionforcefield/ExternalForceField.inl \
           interactionforcefield/RepulsiveSpringForceField.h \
           interactionforcefield/RepulsiveSpringForceField.inl \
           interactionforcefield/InteractionEllipsoidForceField.h \
           interactionforcefield/InteractionEllipsoidForceField.inl \
           mapping/ArticulatedSystemMapping.h \
           mapping/ArticulatedSystemMapping.inl \
           mapping/BarycentricMapping.h \
           mapping/BarycentricMapping.inl \
           mapping/BeamLinearMapping.h \
           mapping/BeamLinearMapping.inl \
           mapping/IdentityMapping.h \
           mapping/IdentityMapping.inl \
           mapping/ImplicitSurfaceMapping.h \
           mapping/ImplicitSurfaceMapping.inl \
           mapping/LaparoscopicRigidMapping.h \
           mapping/LaparoscopicRigidMapping.inl \
           mapping/LineSetSkinningMapping.h \
           mapping/LineSetSkinningMapping.inl \
           mapping/RigidMapping.h \
           mapping/RigidMapping.inl \
           mapping/RigidRigidMapping.h \
           mapping/RigidRigidMapping.inl \
           mapping/SkinningMapping.h \
           mapping/SkinningMapping.inl \
           mapping/SPHFluidSurfaceMapping.h \
           mapping/SPHFluidSurfaceMapping.inl \
           mapping/SubsetMapping.h \
           mapping/SubsetMapping.inl \
           mapping/SurfaceIdentityMapping.h \
           mass/DiagonalMass.h \
           mass/DiagonalMass.inl \
           mass/MatrixMass.h \
           mass/MatrixMass.inl \
           mass/UniformMass.h \
           mass/UniformMass.inl \
           misc/ReadState.h \
           misc/ReadState.inl \
           misc/WriteState.h \
           misc/WriteState.inl \
           mastersolver/DefaultMasterSolver.h \
           odesolver/BiCGStabImplicitSolver.h \
           odesolver/CGImplicitSolver.h \
           odesolver/ComplianceArticulatedSystemSolver.h \
           odesolver/ComplianceCGImplicitSolver.h \
           odesolver/ComplianceEulerSolver.h \
           odesolver/DampVelocitySolver.h \
           odesolver/MasterContactSolver.h \
           odesolver/EulerSolver.h \
           odesolver/NewMatSolver.h \
           odesolver/RungeKutta2Solver.h \
           odesolver/RungeKutta4Solver.h \
           odesolver/StaticSolver.h \
           topology/CubeTopology.h \
           topology/EdgeData.h \
           topology/EdgeData.inl \
           topology/EdgeSubsetData.h \
           topology/EdgeSubsetData.inl \
           topology/EdgeSetTopology.h \
           topology/EdgeSetTopology.inl \
           topology/FittedRegularGridTopology.h \
           topology/GridTopology.h \
           topology/MeshTopology.h \
           topology/PointData.h \
           topology/PointData.inl \
           topology/PointSetTopology.h \
           topology/PointSetTopology.inl \
           topology/PointSubset.h \
           topology/RegularGridTopology.h \
           topology/SparseGridTopology.h \
           topology/TopologyChangedEvent.h \
           topology/TetrahedronData.h \
           topology/TetrahedronData.inl \
           topology/TriangleData.h \
           topology/TriangleData.inl \
           topology/TriangleSubsetData.h \
           topology/TriangleSubsetData.inl \
     	   topology/HexahedronData.h \
           topology/HexahedronData.inl \
	   topology/QuadData.h \
           topology/QuadData.inl \
           topology/TriangleSetTopology.h \
           topology/TriangleSetTopology.inl \
	   topology/TetrahedronSetTopology.h \
           topology/TetrahedronSetTopology.inl \
           topology/QuadSetTopology.h \
           topology/QuadSetTopology.inl \
	     topology/HexahedronSetTopology.h \
           topology/HexahedronSetTopology.inl \
	     topology/Tetra2TriangleTopologicalMapping.h \
	     topology/Tetra2TriangleTopologicalMapping.inl \
           visualmodel/DrawV.h \
           visualmodel/OglModel.h \
           visualmodel/VisualModelImpl.h \
	   visualmodel/Light.h \
	   visualmodel/OglShader.h
           
SOURCES += MappedObject.cpp \
           MechanicalObject.cpp \
           ArticulatedBody.cpp \
           FreeJoint.cpp \
           Joint.cpp \
           RevoluteJoint.cpp \
           behaviormodel/eulerianfluid/Fluid2D.cpp \
           behaviormodel/eulerianfluid/Fluid3D.cpp \
           behaviormodel/eulerianfluid/Grid2D.cpp \
           behaviormodel/eulerianfluid/Grid3D.cpp \
           collision/BarycentricStickContact.cpp \
           collision/BarycentricLagrangianMultiplierContact.cpp \
           collision/BarycentricPenalityContact.cpp \
           collision/BruteForceDetection.cpp \
           collision/ContactCorrection.cpp \
           collision/ContinuousIntersection.cpp \
           collision/ContinuousTriangleIntersection.cpp \
           collision/CubeModel.cpp \
           collision/CuttingManager.cpp \
           collision/CarvingManager.cpp \
           collision/DefaultCollisionGroupManager.cpp \
           collision/DefaultContactManager.cpp \
           collision/DefaultPipeline.cpp \
           collision/DiscreteIntersection.cpp \
           collision/DistanceGridCollisionModel.cpp \
           collision/LineModel.cpp \
           collision/EdgeRemoveContact.cpp \
           collision/GraspingManager.cpp \
           collision/FractureManager.cpp \
           collision/FrictionContact.cpp \
           collision/MinProximityIntersection.cpp \
           collision/NewProximityIntersection.cpp \
           collision/RayTraceDetection.cpp \
           collision/PointModel.cpp \
           collision/proximity.cpp \
           collision/ProximityIntersection.cpp \
           collision/RayContact.cpp \
           collision/RayModel.cpp \
           collision/RayPickInteractor.cpp \
           collision/RayTriangleIntersection.cpp \
           collision/SharpLineModel.cpp \
           collision/SphereModel.cpp \
           collision/SphereTreeModel.cpp \
           collision/TestDetection.cpp \
           collision/TriangleModel.cpp \
           collision/TriangleOctree.cpp \
           collision/TriangleOctreeModel.cpp \
	   collision/TriangularFEMFractureManager.cpp \
           constraint/BoxConstraint.cpp \
           constraint/FixedConstraint.cpp \
           constraint/FixedPlaneConstraint.cpp \
           constraint/LagrangianMultiplierAttachConstraint.cpp \
           constraint/LagrangianMultiplierContactConstraint.cpp \
           constraint/LagrangianMultiplierFixedConstraint.cpp \
           constraint/OscillatorConstraint.cpp \
           constraint/UnilateralInteractionConstraint.cpp \
           constraint/LinearMovementConstraint.cpp \
           container/ArticulatedHierarchyContainer.cpp \
           contextobject/CoordinateSystem.cpp \
           contextobject/Gravity.cpp \
           contextobject/GuidedCoordinateSystem.cpp \
           forcefield/BeamFEMForceField.cpp \
           forcefield/ConstantForceField.cpp \
           forcefield/EdgePressureForceField.cpp \
           forcefield/LennardJonesForceField.cpp \
           forcefield/PlaneForceField.cpp \
           forcefield/SphereForceField.cpp \
	   forcefield/ConicalForceField.cpp \
           forcefield/EllipsoidForceField.cpp \
           forcefield/SPHFluidForceField.cpp \
           forcefield/SpringForceField.cpp \
           forcefield/StiffSpringForceField.cpp \
           forcefield/JointSpringForceField.cpp \
           forcefield/PenalityContactForceField.cpp \
           forcefield/MeshSpringForceField.cpp \
           forcefield/QuadBendingSprings.cpp \
           forcefield/RegularGridSpringForceField.cpp \
           forcefield/TetrahedronFEMForceField.cpp \
           forcefield/HexahedronFEMForceField.cpp \
	   forcefield/HexahedronFEMForceFieldAndMass.cpp \
           forcefield/TetrahedralTensorMassForceField.cpp \
           forcefield/TetrahedralBiquadraticSpringsForceField.cpp \
           forcefield/TetrahedralCorotationalFEMForceField.cpp \
           forcefield/TetrahedralQuadraticSpringsForceField.cpp \
           forcefield/TriangleBendingSprings.cpp \
	     forcefield/TriangularBendingSprings.cpp \
           forcefield/TriangleFEMForceField.cpp \
           forcefield/TriangularFEMForceField.cpp \
           forcefield/TrianglePressureForceField.cpp \
           forcefield/TriangularBiquadraticSpringsForceField.cpp \
           forcefield/TriangularQuadraticSpringsForceField.cpp \
           forcefield/TriangularTensorMassForceField.cpp \
           forcefield/VectorSpringForceField.cpp \
           forcefield/WashingMachineForceField.cpp \
           interactionforcefield/ExternalForceField.cpp \
           interactionforcefield/RepulsiveSpringForceField.cpp \
           interactionforcefield/InteractionEllipsoidForceField.cpp \
           mapping/ArticulatedSystemMapping.cpp \
           mapping/BarycentricMapping.cpp \
           mapping/BeamLinearMapping.cpp \
           mapping/IdentityMapping.cpp \
           mapping/ImplicitSurfaceMapping.cpp \
           mapping/LaparoscopicRigidMapping.cpp \
           mapping/RigidMapping.cpp \
           mapping/RigidRigidMapping.cpp \
           mapping/LineSetSkinningMapping.cpp \
           mapping/SkinningMapping.cpp \
           mapping/SPHFluidSurfaceMapping.cpp \
           mapping/SubsetMapping.cpp \
           mapping/SurfaceIdentityMapping.cpp \
           mass/DiagonalMass.cpp \
           mass/MatrixMass.cpp \
           mass/UniformMass.cpp \
           misc/ReadState.cpp \
           misc/WriteState.cpp \
           mastersolver/DefaultMasterSolver.cpp \
           odesolver/CGImplicitSolver.cpp \
           odesolver/EulerSolver.cpp \
           odesolver/ComplianceArticulatedSystemSolver.cpp \
           odesolver/ComplianceCGImplicitSolver.cpp \
           odesolver/ComplianceEulerSolver.cpp \
           odesolver/DampVelocitySolver.cpp \
           odesolver/MasterContactSolver.cpp \
           odesolver/NewMatSolver.cpp \
           odesolver/RungeKutta2Solver.cpp \
           odesolver/RungeKutta4Solver.cpp \
           odesolver/StaticSolver.cpp \
           odesolver/BiCGStabImplicitSolver.cpp \
           topology/CubeTopology.cpp \
           topology/EdgeSetTopology.cpp \
           topology/FittedRegularGridTopology.cpp \
           topology/GridTopology.cpp \
           topology/MeshTopology.cpp \
           topology/PointData.cpp \
           topology/PointSetTopology.cpp \
           topology/PointSubset.cpp \
           topology/RegularGridTopology.cpp \
           topology/SparseGridTopology.cpp \
           topology/TriangleSetTopology.cpp \
	     topology/TetrahedronSetTopology.cpp \
           topology/QuadSetTopology.cpp \
 	     topology/HexahedronSetTopology.cpp \
	     topology/Tetra2TriangleTopologicalMapping.cpp \
           visualmodel/DrawV.cpp \
           visualmodel/OglModel.cpp \
           visualmodel/VisualModelImpl.cpp \
	   visualmodel/Light.cpp \
	   visualmodel/OglShader.cpp


LIBS += $$SOFA_FRAMEWORK_LIBS
LIBS += -lsofasimulation$$LIBSUFFIX 
LIBS += $$SOFA_EXT_LIBS 

macx: LIBS += -framework GLUT 

# Make sure there are no cross-dependencies
INCLUDEPATH -= $$SOFA_DIR/applications

contains(DEFINES,SOFA_TEST_FRICTION) {

HEADERS += forcefield/PenalityContactFrictionForceField.h \
           forcefield/PenalityContactFrictionForceField.inl

SOURCES += forcefield/PenalityContactFrictionForceField.cpp \

}

contains(DEFINES,SOFA_HAVE_MKL) {

HEADERS += \
	odesolver/MKLSolver.h
	
SOURCES += \
	odesolver/MKLSolver.cpp

}
