/******************************************************************************
*       SOFA, Simulation Open-Framework Architecture, version 1.0 beta 4      *
*                (c) 2006-2009 MGH, INRIA, USTL, UJF, CNRS                    *
*                                                                             *
* This library is free software; you can redistribute it and/or modify it     *
* under the terms of the GNU Lesser General Public License as published by    *
* the Free Software Foundation; either version 2.1 of the License, or (at     *
* your option) any later version.                                             *
*                                                                             *
* This library is distributed in the hope that it will be useful, but WITHOUT *
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or       *
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License *
* for more details.                                                           *
*                                                                             *
* You should have received a copy of the GNU Lesser General Public License    *
* along with this library; if not, write to the Free Software Foundation,     *
* Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA.          *
*******************************************************************************
*                               SOFA :: Modules                               *
*                                                                             *
* Authors: The SOFA Team and external contributors (see Authors.txt)          *
*                                                                             *
* Contact information: contact@sofa-framework.org                             *
******************************************************************************/



// File automatically generated by "generateTypedef"


#ifndef SOFA_TYPEDEF_Constraint_double_H
#define SOFA_TYPEDEF_Constraint_double_H

//Default files containing the declaration of the vector type
#include <sofa/defaulttype/VecTypes.h>
#include <sofa/defaulttype/RigidTypes.h>
#include <sofa/defaulttype/Mat.h>



#include <sofa/component/constraint/AttachConstraint.h>
#include <sofa/component/constraint/FixedConstraint.h>
#include <sofa/component/constraint/FixedPlaneConstraint.h>
#include <sofa/component/constraint/FixedRotationConstraint.h>
#include <sofa/component/constraint/FixedTranslationConstraint.h>
#include <sofa/component/constraint/HermiteSplineConstraint.h>
#include <sofa/component/constraint/LinearMovementConstraint.h>
#include <sofa/component/constraint/LinearVelocityConstraint.h>
#include <sofa/component/constraint/OscillatorConstraint.h>
#include <sofa/component/constraint/ParabolicConstraint.h>
#include <sofa/component/misc/ParticleSink.h>
#include <sofa/component/misc/ParticleSource.h>
#include <sofa/component/constraint/UnilateralInteractionConstraint.h>



//---------------------------------------------------------------------------------------------
//Typedef for AttachConstraint
typedef sofa::component::constraint::AttachConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, double>, sofa::defaulttype::Vec<3, double>, double> > AttachConstraint3d;
typedef sofa::component::constraint::AttachConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<2, double>, sofa::defaulttype::Vec<2, double>, double> > AttachConstraint1d;
typedef sofa::component::constraint::AttachConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<1, double>, sofa::defaulttype::Vec<1, double>, double> > AttachConstraint2d;
typedef sofa::component::constraint::AttachConstraint<sofa::defaulttype::StdRigidTypes<3, double> > AttachConstraintRigid3d;
typedef sofa::component::constraint::AttachConstraint<sofa::defaulttype::StdRigidTypes<2, double> > AttachConstraintRigid2d;



//---------------------------------------------------------------------------------------------
//Typedef for FixedConstraint
typedef sofa::component::constraint::FixedConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, double>, sofa::defaulttype::Vec<3, double>, double> > FixedConstraint3d;
typedef sofa::component::constraint::FixedConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<2, double>, sofa::defaulttype::Vec<2, double>, double> > FixedConstraint1d;
typedef sofa::component::constraint::FixedConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<1, double>, sofa::defaulttype::Vec<1, double>, double> > FixedConstraint2d;
typedef sofa::component::constraint::FixedConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<6, double>, sofa::defaulttype::Vec<6, double>, double> > FixedConstraint6d;
typedef sofa::component::constraint::FixedConstraint<sofa::defaulttype::StdRigidTypes<3, double> > FixedConstraintRigid3d;
typedef sofa::component::constraint::FixedConstraint<sofa::defaulttype::StdRigidTypes<2, double> > FixedConstraintRigid2d;



//---------------------------------------------------------------------------------------------
//Typedef for FixedPlaneConstraint
typedef sofa::component::constraint::FixedPlaneConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, double>, sofa::defaulttype::Vec<3, double>, double> > FixedPlaneConstraint3d;
typedef sofa::component::constraint::FixedPlaneConstraint<sofa::defaulttype::StdRigidTypes<3, double> > FixedPlaneConstraintRigid3d;



//---------------------------------------------------------------------------------------------
//Typedef for FixedRotationConstraint
typedef sofa::component::constraint::FixedRotationConstraint<sofa::defaulttype::StdRigidTypes<3, double> > FixedRotationConstraintRigid3d;



//---------------------------------------------------------------------------------------------
//Typedef for FixedTranslationConstraint
typedef sofa::component::constraint::FixedTranslationConstraint<sofa::defaulttype::StdRigidTypes<3, double> > FixedTranslationConstraintRigid3d;
typedef sofa::component::constraint::FixedTranslationConstraint<sofa::defaulttype::StdRigidTypes<2, double> > FixedTranslationConstraintRigid2d;



//---------------------------------------------------------------------------------------------
//Typedef for HermiteSplineConstraint
typedef sofa::component::constraint::HermiteSplineConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, double>, sofa::defaulttype::Vec<3, double>, double> > HermiteSplineConstraint3d;
typedef sofa::component::constraint::HermiteSplineConstraint<sofa::defaulttype::StdRigidTypes<3, double> > HermiteSplineConstraintRigid3d;



//---------------------------------------------------------------------------------------------
//Typedef for LinearMovementConstraint
typedef sofa::component::constraint::LinearMovementConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, double>, sofa::defaulttype::Vec<3, double>, double> > LinearMovementConstraint3d;
typedef sofa::component::constraint::LinearMovementConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<2, double>, sofa::defaulttype::Vec<2, double>, double> > LinearMovementConstraint1d;
typedef sofa::component::constraint::LinearMovementConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<1, double>, sofa::defaulttype::Vec<1, double>, double> > LinearMovementConstraint2d;
typedef sofa::component::constraint::LinearMovementConstraint<sofa::defaulttype::StdRigidTypes<3, double> > LinearMovementConstraintRigid3d;



//---------------------------------------------------------------------------------------------
//Typedef for LinearVelocityConstraint
typedef sofa::component::constraint::LinearVelocityConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, double>, sofa::defaulttype::Vec<3, double>, double> > LinearVelocityConstraint3d;
typedef sofa::component::constraint::LinearVelocityConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<2, double>, sofa::defaulttype::Vec<2, double>, double> > LinearVelocityConstraint1d;
typedef sofa::component::constraint::LinearVelocityConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<1, double>, sofa::defaulttype::Vec<1, double>, double> > LinearVelocityConstraint2d;
typedef sofa::component::constraint::LinearVelocityConstraint<sofa::defaulttype::StdRigidTypes<3, double> > LinearVelocityConstraintRigid3d;



//---------------------------------------------------------------------------------------------
//Typedef for OscillatorConstraint
typedef sofa::component::constraint::OscillatorConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, double>, sofa::defaulttype::Vec<3, double>, double> > OscillatorConstraint3d;
typedef sofa::component::constraint::OscillatorConstraint<sofa::defaulttype::StdRigidTypes<3, double> > OscillatorConstraintRigid3d;



//---------------------------------------------------------------------------------------------
//Typedef for ParabolicConstraint
typedef sofa::component::constraint::ParabolicConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, double>, sofa::defaulttype::Vec<3, double>, double> > ParabolicConstraint3d;
typedef sofa::component::constraint::ParabolicConstraint<sofa::defaulttype::StdRigidTypes<3, double> > ParabolicConstraintRigid3d;



//---------------------------------------------------------------------------------------------
//Typedef for ParticleSink
typedef sofa::component::misc::ParticleSink<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, double>, sofa::defaulttype::Vec<3, double>, double> > ParticleSink3d;
typedef sofa::component::misc::ParticleSink<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<2, double>, sofa::defaulttype::Vec<2, double>, double> > ParticleSink1d;



//---------------------------------------------------------------------------------------------
//Typedef for ParticleSource
typedef sofa::component::misc::ParticleSource<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, double>, sofa::defaulttype::Vec<3, double>, double> > ParticleSource3d;
typedef sofa::component::misc::ParticleSource<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<2, double>, sofa::defaulttype::Vec<2, double>, double> > ParticleSource1d;



//---------------------------------------------------------------------------------------------
//Typedef for UnilateralInteractionConstraint
typedef sofa::component::constraint::UnilateralInteractionConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, double>, sofa::defaulttype::Vec<3, double>, double> > UnilateralInteractionConstraint3d;





#ifndef SOFA_FLOAT
typedef AttachConstraint3d AttachConstraint3;
typedef AttachConstraint1d AttachConstraint1;
typedef AttachConstraint2d AttachConstraint2;
typedef AttachConstraintRigid3d AttachConstraintRigid3;
typedef AttachConstraintRigid2d AttachConstraintRigid2;
typedef FixedConstraint3d FixedConstraint3;
typedef FixedConstraint1d FixedConstraint1;
typedef FixedConstraint2d FixedConstraint2;
typedef FixedConstraint6d FixedConstraint6;
typedef FixedConstraintRigid3d FixedConstraintRigid3;
typedef FixedConstraintRigid2d FixedConstraintRigid2;
typedef FixedPlaneConstraint3d FixedPlaneConstraint3;
typedef FixedPlaneConstraintRigid3d FixedPlaneConstraintRigid3;
typedef FixedRotationConstraintRigid3d FixedRotationConstraintRigid3;
typedef FixedTranslationConstraintRigid3d FixedTranslationConstraintRigid3;
typedef FixedTranslationConstraintRigid2d FixedTranslationConstraintRigid2;
typedef HermiteSplineConstraint3d HermiteSplineConstraint3;
typedef HermiteSplineConstraintRigid3d HermiteSplineConstraintRigid3;
typedef LinearMovementConstraint3d LinearMovementConstraint3;
typedef LinearMovementConstraint1d LinearMovementConstraint1;
typedef LinearMovementConstraint2d LinearMovementConstraint2;
typedef LinearMovementConstraintRigid3d LinearMovementConstraintRigid3;
typedef LinearVelocityConstraint3d LinearVelocityConstraint3;
typedef LinearVelocityConstraint1d LinearVelocityConstraint1;
typedef LinearVelocityConstraint2d LinearVelocityConstraint2;
typedef LinearVelocityConstraintRigid3d LinearVelocityConstraintRigid3;
typedef OscillatorConstraint3d OscillatorConstraint3;
typedef OscillatorConstraintRigid3d OscillatorConstraintRigid3;
typedef ParabolicConstraint3d ParabolicConstraint3;
typedef ParabolicConstraintRigid3d ParabolicConstraintRigid3;
typedef ParticleSink3d ParticleSink3;
typedef ParticleSink1d ParticleSink1;
typedef ParticleSource3d ParticleSource3;
typedef ParticleSource1d ParticleSource1;
typedef UnilateralInteractionConstraint3d UnilateralInteractionConstraint3;
#endif

#endif
