/******************************************************************************
*       SOFA, Simulation Open-Framework Architecture, version 1.0 beta 4      *
*                (c) 2006-2009 MGH, INRIA, USTL, UJF, CNRS                    *
*                                                                             *
* This library is free software; you can redistribute it and/or modify it     *
* under the terms of the GNU Lesser General Public License as published by    *
* the Free Software Foundation; either version 2.1 of the License, or (at     *
* your option) any later version.                                             *
*                                                                             *
* This library is distributed in the hope that it will be useful, but WITHOUT *
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or       *
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License *
* for more details.                                                           *
*                                                                             *
* You should have received a copy of the GNU Lesser General Public License    *
* along with this library; if not, write to the Free Software Foundation,     *
* Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA.          *
*******************************************************************************
*                               SOFA :: Modules                               *
*                                                                             *
* Authors: The SOFA Team and external contributors (see Authors.txt)          *
*                                                                             *
* Contact information: contact@sofa-framework.org                             *
******************************************************************************/



// File automatically generated by "generateTypedef"


#ifndef SOFA_TYPEDEF_Constraint_float_H
#define SOFA_TYPEDEF_Constraint_float_H

//Default files containing the declaration of the vector type
#include <sofa/defaulttype/VecTypes.h>
#include <sofa/defaulttype/RigidTypes.h>
#include <sofa/defaulttype/Mat.h>



#include <sofa/component/constraint/AttachConstraint.h>
#include <sofa/component/constraint/DistanceConstraint.h>
#include <sofa/component/constraint/FixedConstraint.h>
#include <sofa/component/constraint/FixedPlaneConstraint.h>
#include <sofa/component/constraint/HermiteSplineConstraint.h>
#include <sofa/component/constraint/LinearMovementConstraint.h>
#include <sofa/component/constraint/LinearVelocityConstraint.h>
#include <sofa/component/constraint/OscillatorConstraint.h>
#include <sofa/component/constraint/ParabolicConstraint.h>
#include <sofa/component/misc/ParticleSink.h>
#include <sofa/component/misc/ParticleSource.h>
#include <sofa/component/constraint/UnilateralInteractionConstraint.h>



//---------------------------------------------------------------------------------------------
//Typedef for AttachConstraint
typedef sofa::component::constraint::AttachConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, float>, sofa::defaulttype::Vec<3, float>, float> > AttachConstraint3f;
typedef sofa::component::constraint::AttachConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<2, float>, sofa::defaulttype::Vec<2, float>, float> > AttachConstraint1f;
typedef sofa::component::constraint::AttachConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<1, float>, sofa::defaulttype::Vec<1, float>, float> > AttachConstraint2f;
typedef sofa::component::constraint::AttachConstraint<sofa::defaulttype::StdRigidTypes<3, float> > AttachConstraintRigid3f;
typedef sofa::component::constraint::AttachConstraint<sofa::defaulttype::StdRigidTypes<2, float> > AttachConstraintRigid2f;



//---------------------------------------------------------------------------------------------
//Typedef for DistanceConstraint
typedef sofa::component::constraint::DistanceConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, float>, sofa::defaulttype::Vec<3, float>, float> > DistanceConstraint3f;
typedef sofa::component::constraint::DistanceConstraint<sofa::defaulttype::StdRigidTypes<3, float> > DistanceConstraintRigid3f;



//---------------------------------------------------------------------------------------------
//Typedef for FixedConstraint
typedef sofa::component::constraint::FixedConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, float>, sofa::defaulttype::Vec<3, float>, float> > FixedConstraint3f;
typedef sofa::component::constraint::FixedConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<2, float>, sofa::defaulttype::Vec<2, float>, float> > FixedConstraint1f;
typedef sofa::component::constraint::FixedConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<1, float>, sofa::defaulttype::Vec<1, float>, float> > FixedConstraint2f;
typedef sofa::component::constraint::FixedConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<6, float>, sofa::defaulttype::Vec<6, float>, float> > FixedConstraint6f;
typedef sofa::component::constraint::FixedConstraint<sofa::defaulttype::StdRigidTypes<3, float> > FixedConstraintRigid3f;
typedef sofa::component::constraint::FixedConstraint<sofa::defaulttype::StdRigidTypes<2, float> > FixedConstraintRigid2f;



//---------------------------------------------------------------------------------------------
//Typedef for FixedPlaneConstraint
typedef sofa::component::constraint::FixedPlaneConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, float>, sofa::defaulttype::Vec<3, float>, float> > FixedPlaneConstraint3f;
typedef sofa::component::constraint::FixedPlaneConstraint<sofa::defaulttype::StdRigidTypes<3, float> > FixedPlaneConstraintRigid3f;



//---------------------------------------------------------------------------------------------
//Typedef for HermiteSplineConstraint
typedef sofa::component::constraint::HermiteSplineConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, float>, sofa::defaulttype::Vec<3, float>, float> > HermiteSplineConstraint3f;
typedef sofa::component::constraint::HermiteSplineConstraint<sofa::defaulttype::StdRigidTypes<3, float> > HermiteSplineConstraintRigid3f;



//---------------------------------------------------------------------------------------------
//Typedef for LinearMovementConstraint
typedef sofa::component::constraint::LinearMovementConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, float>, sofa::defaulttype::Vec<3, float>, float> > LinearMovementConstraint3f;
typedef sofa::component::constraint::LinearMovementConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<2, float>, sofa::defaulttype::Vec<2, float>, float> > LinearMovementConstraint1f;
typedef sofa::component::constraint::LinearMovementConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<1, float>, sofa::defaulttype::Vec<1, float>, float> > LinearMovementConstraint2f;
typedef sofa::component::constraint::LinearMovementConstraint<sofa::defaulttype::StdRigidTypes<3, float> > LinearMovementConstraintRigid3f;



//---------------------------------------------------------------------------------------------
//Typedef for LinearVelocityConstraint
typedef sofa::component::constraint::LinearVelocityConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, float>, sofa::defaulttype::Vec<3, float>, float> > LinearVelocityConstraint3f;
typedef sofa::component::constraint::LinearVelocityConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<2, float>, sofa::defaulttype::Vec<2, float>, float> > LinearVelocityConstraint1f;
typedef sofa::component::constraint::LinearVelocityConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<1, float>, sofa::defaulttype::Vec<1, float>, float> > LinearVelocityConstraint2f;
typedef sofa::component::constraint::LinearVelocityConstraint<sofa::defaulttype::StdRigidTypes<3, float> > LinearVelocityConstraintRigid3f;



//---------------------------------------------------------------------------------------------
//Typedef for OscillatorConstraint
typedef sofa::component::constraint::OscillatorConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, float>, sofa::defaulttype::Vec<3, float>, float> > OscillatorConstraint3f;
typedef sofa::component::constraint::OscillatorConstraint<sofa::defaulttype::StdRigidTypes<3, float> > OscillatorConstraintRigid3f;



//---------------------------------------------------------------------------------------------
//Typedef for ParabolicConstraint
typedef sofa::component::constraint::ParabolicConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, float>, sofa::defaulttype::Vec<3, float>, float> > ParabolicConstraint3f;
typedef sofa::component::constraint::ParabolicConstraint<sofa::defaulttype::StdRigidTypes<3, float> > ParabolicConstraintRigid3f;



//---------------------------------------------------------------------------------------------
//Typedef for ParticleSink
typedef sofa::component::misc::ParticleSink<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, float>, sofa::defaulttype::Vec<3, float>, float> > ParticleSink3f;
typedef sofa::component::misc::ParticleSink<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<2, float>, sofa::defaulttype::Vec<2, float>, float> > ParticleSink1f;



//---------------------------------------------------------------------------------------------
//Typedef for ParticleSource
typedef sofa::component::misc::ParticleSource<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, float>, sofa::defaulttype::Vec<3, float>, float> > ParticleSource3f;
typedef sofa::component::misc::ParticleSource<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<2, float>, sofa::defaulttype::Vec<2, float>, float> > ParticleSource1f;



//---------------------------------------------------------------------------------------------
//Typedef for UnilateralInteractionConstraint
typedef sofa::component::constraint::UnilateralInteractionConstraint<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, float>, sofa::defaulttype::Vec<3, float>, float> > UnilateralInteractionConstraint3f;





#ifdef SOFA_FLOAT
typedef AttachConstraint3f AttachConstraint3;
typedef AttachConstraint1f AttachConstraint1;
typedef AttachConstraint2f AttachConstraint2;
typedef AttachConstraintRigid3f AttachConstraintRigid3;
typedef AttachConstraintRigid2f AttachConstraintRigid2;
typedef DistanceConstraint3f DistanceConstraint3;
typedef DistanceConstraintRigid3f DistanceConstraintRigid3;
typedef FixedConstraint3f FixedConstraint3;
typedef FixedConstraint1f FixedConstraint1;
typedef FixedConstraint2f FixedConstraint2;
typedef FixedConstraint6f FixedConstraint6;
typedef FixedConstraintRigid3f FixedConstraintRigid3;
typedef FixedConstraintRigid2f FixedConstraintRigid2;
typedef FixedPlaneConstraint3f FixedPlaneConstraint3;
typedef FixedPlaneConstraintRigid3f FixedPlaneConstraintRigid3;
typedef HermiteSplineConstraint3f HermiteSplineConstraint3;
typedef HermiteSplineConstraintRigid3f HermiteSplineConstraintRigid3;
typedef LinearMovementConstraint3f LinearMovementConstraint3;
typedef LinearMovementConstraint1f LinearMovementConstraint1;
typedef LinearMovementConstraint2f LinearMovementConstraint2;
typedef LinearMovementConstraintRigid3f LinearMovementConstraintRigid3;
typedef LinearVelocityConstraint3f LinearVelocityConstraint3;
typedef LinearVelocityConstraint1f LinearVelocityConstraint1;
typedef LinearVelocityConstraint2f LinearVelocityConstraint2;
typedef LinearVelocityConstraintRigid3f LinearVelocityConstraintRigid3;
typedef OscillatorConstraint3f OscillatorConstraint3;
typedef OscillatorConstraintRigid3f OscillatorConstraintRigid3;
typedef ParabolicConstraint3f ParabolicConstraint3;
typedef ParabolicConstraintRigid3f ParabolicConstraintRigid3;
typedef ParticleSink3f ParticleSink3;
typedef ParticleSink1f ParticleSink1;
typedef ParticleSource3f ParticleSource3;
typedef ParticleSource1f ParticleSource1;
typedef UnilateralInteractionConstraint3f UnilateralInteractionConstraint3;
#endif

#endif
