/******************************************************************************
*       SOFA, Simulation Open-Framework Architecture, version 1.0 beta 4      *
*                (c) 2006-2009 MGH, INRIA, USTL, UJF, CNRS                    *
*                                                                             *
* This library is free software; you can redistribute it and/or modify it     *
* under the terms of the GNU Lesser General Public License as published by    *
* the Free Software Foundation; either version 2.1 of the License, or (at     *
* your option) any later version.                                             *
*                                                                             *
* This library is distributed in the hope that it will be useful, but WITHOUT *
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or       *
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License *
* for more details.                                                           *
*                                                                             *
* You should have received a copy of the GNU Lesser General Public License    *
* along with this library; if not, write to the Free Software Foundation,     *
* Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA.          *
*******************************************************************************
*                               SOFA :: Modules                               *
*                                                                             *
* Authors: The SOFA Team and external contributors (see Authors.txt)          *
*                                                                             *
* Contact information: contact@sofa-framework.org                             *
******************************************************************************/



// File automatically generated by "generateTypedef"


#ifndef SOFA_TYPEDEF_ConstraintSolver_double_H
#define SOFA_TYPEDEF_ConstraintSolver_double_H

//Default files containing the declaration of the vector type
#include <sofa/defaulttype/VecTypes.h>
#include <sofa/defaulttype/RigidTypes.h>
#include <sofa/defaulttype/Mat.h>



#include <sofa/component/constraint/LinearSolverConstraintCorrection.h>
#include <sofa/component/constraint/PrecomputedConstraintCorrection.h>
#include <sofa/component/constraint/UncoupledConstraintCorrection.h>



//---------------------------------------------------------------------------------------------
//Typedef for LinearSolverConstraintCorrection
typedef sofa::component::constraint::LinearSolverConstraintCorrection<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, double>, sofa::defaulttype::Vec<3, double>, double> > LinearSolverConstraintCorrection3d;
typedef sofa::component::constraint::LinearSolverConstraintCorrection<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<1, double>, sofa::defaulttype::Vec<1, double>, double> > LinearSolverConstraintCorrection2d;
typedef sofa::component::constraint::LinearSolverConstraintCorrection<sofa::defaulttype::StdRigidTypes<3, double> > LinearSolverConstraintCorrectionRigid3d;



//---------------------------------------------------------------------------------------------
//Typedef for PrecomputedConstraintCorrection
typedef sofa::component::constraint::PrecomputedConstraintCorrection<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, double>, sofa::defaulttype::Vec<3, double>, double> > PrecomputedConstraintCorrection3d;
typedef sofa::component::constraint::PrecomputedConstraintCorrection<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<1, double>, sofa::defaulttype::Vec<1, double>, double> > PrecomputedConstraintCorrection2d;
typedef sofa::component::constraint::PrecomputedConstraintCorrection<sofa::defaulttype::StdRigidTypes<3, double> > PrecomputedConstraintCorrectionRigid3d;



//---------------------------------------------------------------------------------------------
//Typedef for UncoupledConstraintCorrection
typedef sofa::component::constraint::UncoupledConstraintCorrection<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<1, double>, sofa::defaulttype::Vec<1, double>, double> > UncoupledConstraintCorrection2d;
typedef sofa::component::constraint::UncoupledConstraintCorrection<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, double>, sofa::defaulttype::Vec<3, double>, double> > UncoupledConstraintCorrection3d;
typedef sofa::component::constraint::UncoupledConstraintCorrection<sofa::defaulttype::StdRigidTypes<3, double> > UncoupledConstraintCorrectionRigid3d;





#ifndef SOFA_FLOAT
typedef LinearSolverConstraintCorrection3d LinearSolverConstraintCorrection3;
typedef LinearSolverConstraintCorrection2d LinearSolverConstraintCorrection2;
typedef LinearSolverConstraintCorrectionRigid3d LinearSolverConstraintCorrectionRigid3;
typedef PrecomputedConstraintCorrection3d PrecomputedConstraintCorrection3;
typedef PrecomputedConstraintCorrection2d PrecomputedConstraintCorrection2;
typedef PrecomputedConstraintCorrectionRigid3d PrecomputedConstraintCorrectionRigid3;
typedef UncoupledConstraintCorrection2d UncoupledConstraintCorrection2;
typedef UncoupledConstraintCorrection3d UncoupledConstraintCorrection3;
typedef UncoupledConstraintCorrectionRigid3d UncoupledConstraintCorrectionRigid3;
#endif

#endif
