# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is an application:  run

HEADERS += ArticulatedSolid.h \
           ArticulatedSolid.inl \
           ArticulatedSolidNode.h \
           ArticulatedSolidTypes.h \
           ArticulatedSolidRevolute.h \
           ArticulatedSolidEulerXYZ.h \
           ArticulatedSolidEulerXYZ.inl \
           ArticulatedSolidRevolute.inl
SOURCES += Main.cpp \
           ArticulatedSolid.cpp \
           ArticulatedSolidNode.cpp \
           ArticulatedSolidTypes.cpp \
           ArticulatedSolidRevolute.cpp \
           ArticulatedSolidEulerXYZ.cpp 
include(../Testing.cfg)
TARGET = run
