# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is an application:  eulerStabilized

HEADERS += EulerStabilizedSolver.h \
           ProceduralScene.h 
SOURCES += Main.cpp \
           EulerStabilizedSolver.cpp \
           ProceduralScene.cpp 
include(../Projects.cfg)
TEMPLATE = app
TARGET = eulerStabilized
CONFIG += debug
