/*******************************************************************************
*       SOFA, Simulation Open-Framework Architecture, version 1.0 beta 1       *
*                (c) 2006-2007 MGH, INRIA, USTL, UJF, CNRS                     *
*                                                                              *
* This program is free software; you can redistribute it and/or modify it      *
* under the terms of the GNU General Public License as published by the Free   *
* Software Foundation; either version 2 of the License, or (at your option)    *
* any later version.                                                           *
*                                                                              *
* This program is distributed in the hope that it will be useful, but WITHOUT  *
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or        *
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for     *
* more details.                                                                *
*                                                                              *
* You should have received a copy of the GNU General Public License along with *
* this program; if not, write to the Free Software Foundation, Inc., 51        *
* Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.                    *
*                                                                              *
* Contact information: contact@sofa-framework.org                              *
*                                                                              *
* Authors: J. Allard, P-J. Bensoussan, S. Cotin, C. Duriez, H. Delingette,     *
* F. Faure, S. Fonteneau, L. Heigeas, C. Mendoza, M. Nesme, P. Neumann,        *
* and F. Poyer                                                                 *
*******************************************************************************/
// generated by Fast Light User Interface Designer (fluid) version 1.0105

#ifndef SOFA_GUI_FLTK_GUI_H
#define SOFA_GUI_FLTK_GUI_H

#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Float_Input.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Box.H>
#include "FLTKviewer.h"
#include <FL/Fl_Menu_Button.H>
#include "Callbacks.h"
#include <FL/Fl_Button.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Output.H>

namespace sofa
{

namespace gui
{

namespace fltk
{

class   		UserInterface
{
  public:
	void				show();
						UserInterface(GNode* groot);
  private:
	Fl_Double_Window*	mainWindow;
	Fl_Group*			viewGroup;
  public:
	Fl_Box*				frame;
	FLTKviewer*			viewer;
	Fl_Output*			threadLabel;
	Fl_Output*			fpsLabel;
	Fl_Float_Input*		dt;
  private:
	Fl_Group*			optionsGroup;
	inline void			cb_START_i(Fl_Button*, void*);
	static void			cb_START(Fl_Button*, void*);
	inline void			cb_Reset_i(Fl_Button*, void*);
	static void			cb_Reset(Fl_Button*, void*);
	inline void			cb_Preset_i(Fl_Button*, void*);
	static void			cb_Preset(Fl_Button*, void*);
	inline void			cb_Smooth_i(Fl_Check_Button*, void*);
	static void			cb_Smooth(Fl_Check_Button*, void*);
	inline void			cb_Visual_i(Fl_Check_Button*, void*);
	static void			cb_Visual(Fl_Check_Button*, void*);
	inline void			cb_Behavior_i(Fl_Check_Button*, void*);
	static void			cb_Behavior(Fl_Check_Button*, void*);
	inline void			cb_Collision_i(Fl_Check_Button*, void*);
	static void			cb_Collision(Fl_Check_Button*, void*);
	inline void			cb_Mapping_i(Fl_Check_Button*, void*);
	static void			cb_Mapping(Fl_Check_Button*, void*);
	inline void			cb_Force_i(Fl_Value_Slider*, void*);
	static void			cb_Force(Fl_Value_Slider*, void*);
	inline void			cb_AddThread_i(Fl_Button*, void*);
	static void			cb_AddThread(Fl_Button*, void*);
	inline void			cb_Dt_i(Fl_Float_Input*, void*);
	static void			cb_Dt(Fl_Float_Input*, void*);
  public:
	char				_currentFilename[2048];
};

} // namespace fltk

} // namespace gui

} // namespace sofa

#endif
